Repository eclipse-zenoh/zenoh-c, pull requests merged in 2024-09, with the labels that each got.

#636 cmake clean up
  .github/workflows/ci.yml
  CMakeLists.txt
  README.md
  install/CMakeLists.txt
  install/PackageConfig.cmake.in
  tests/CMakeLists.txt
Labels: enhancement, release

#641 make z_drop on zenoh entities call actual drop instead of undeclare
  include/zenoh_commons.h
  src/publication_cache.rs
  src/publisher.rs
  src/queryable.rs
  src/querying_subscriber.rs
  src/subscriber.rs
Labels: internal, api fix

#642 add missing zenoh-rust functionality
  docs/api.rst
  include/zenoh_commons.h
  src/publication_cache.rs
  src/queryable.rs
Labels: enhancement, api sync

#654 disable build with unstable API by default
  CMakeLists.txt
Labels: bug

#653 move reliability to publisher
  Cargo.lock
  docs/api.rst
  include/zenoh_commons.h
  src/commons.rs
  src/publisher.rs
  src/put.rs
  src/subscriber.rs
Labels: dependencies, release, api sync, api fix

#656 add functionality to iterate over z_bytes slices
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/src/lib.rs
  include/zenoh_commons.h
  src/collections.rs
  src/payload.rs
  tests/z_api_payload_test.c
Labels: enhancement, api sync

#660 add unstable tags to docs
  build-resources/opaque-types/src/lib.rs
  docs/api.rst
  include/zenoh_commons.h
  src/closures/matching_status_closure.rs
  src/closures/zenohid_closure.rs
  src/commons.rs
  src/get.rs
  src/info.rs
  src/keyexpr.rs
  src/liveliness.rs
  src/payload.rs
  src/publication_cache.rs
  src/publisher.rs
  src/put.rs
  src/queryable.rs
  src/querying_subscriber.rs
  src/scouting.rs
  src/session.rs
  src/shm/buffer/zshm.rs
  src/shm/buffer/zshmmut.rs
  src/shm/client/shm_client.rs
  src/shm/client/shm_segment.rs
  src/shm/client_storage/mod.rs
  src/shm/common/types.rs
  src/shm/protocol_implementations/posix/posix_shm_client.rs
  src/shm/protocol_implementations/posix/posix_shm_provider.rs
  src/shm/protocol_implementations/posix/protocol_id.rs
  src/shm/provider/alloc_layout.rs
  src/shm/provider/chunk.rs
  src/shm/provider/shm_provider.rs
  src/shm/provider/shm_provider_backend.rs
  src/shm/provider/types.rs
Labels: documentation

#662 removed internal traits
  Cargo.lock
  src/get.rs
  src/put.rs
  src/queryable.rs
  src/querying_subscriber.rs
Labels: internal

#663 Fix API #647
  include/zenoh_commons.h
  src/shm/buffer/zshmmut.rs
  src/shm/client_storage/mod.rs
  src/shm/provider/types.rs
  tests/z_api_shm_test.c
Labels: enhancement

#648 Add LivelinessSubscriber history option
  src/liveliness.rs
Labels: new feature

#666 Make unstable tags more visible in the docs
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/src/lib.rs
  docs/api.rst
  include/zenoh_commons.h
  src/closures/matching_status_closure.rs
  src/closures/zenohid_closure.rs
  src/commons.rs
  src/get.rs
  src/info.rs
  src/keyexpr.rs
  src/liveliness.rs
  src/payload.rs
  src/publication_cache.rs
  src/publisher.rs
  src/put.rs
  src/queryable.rs
  src/querying_subscriber.rs
  src/scouting.rs
  src/session.rs
  src/shm/buffer/zshm.rs
  src/shm/buffer/zshmmut.rs
  src/shm/client/shm_client.rs
  src/shm/client/shm_segment.rs
  src/shm/client_storage/mod.rs
  src/shm/common/types.rs
  src/shm/protocol_implementations/posix/posix_shm_client.rs
  src/shm/protocol_implementations/posix/posix_shm_provider.rs
  src/shm/protocol_implementations/posix/protocol_id.rs
  src/shm/provider/alloc_layout.rs
  src/shm/provider/chunk.rs
  src/shm/provider/shm_provider.rs
  src/shm/provider/shm_provider_backend.rs
  src/shm/provider/types.rs
Labels: documentation

#668 Align _clone functions
  build-resources/opaque-types/src/lib.rs
  docs/api.rst
  include/zenoh_commons.h
  src/get.rs
  src/keyexpr.rs
  src/session.rs
Labels: api sync, internal

#669 remove z_config_client and z_config_peer
  docs/api.rst
  include/zenoh_commons.h
  src/config.rs
  tests/z_api_config_test.c
Labels: api sync, internal, api fix

#673 Add z_clone macro
  build.rs
  include/zenoh_macros.h
Labels: enhancement

#674 Adopt for recent zenoh res_2_wait
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  include/zenoh_commons.h
  src/querying_subscriber.rs
  src/shm/protocol_implementations/posix/posix_shm_provider.rs
  src/shm/provider/shm_provider.rs
Labels: dependencies, release, api sync

#676 align with new dev/arcsession changes
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/src/lib.rs
  include/zenoh_commons.h
  src/config.rs
  src/info.rs
  src/keyexpr.rs
  src/liveliness.rs
  src/publication_cache.rs
  src/publisher.rs
  src/queryable.rs
  src/querying_subscriber.rs
  src/session.rs
  src/shm/provider/alloc_layout_impl.rs
  src/shm/provider/shm_provider_impl.rs
  src/subscriber.rs
Labels: enhancement, api sync, api fix

#678 add hello and string_array clones
  build-resources/opaque-types/src/lib.rs
  docs/api.rst
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/collections.rs
  src/scouting.rs
Labels: enhancement, api fix

#677 made closure param mutable
  examples/z_ping.c
  examples/z_ping_shm.c
  examples/z_pong.c
  examples/z_query_sub.c
  examples/z_queryable.c
  examples/z_queryable_shm.c
  examples/z_scout.c
  examples/z_sub.c
  examples/z_sub_attachment.c
  examples/z_sub_liveliness.c
  examples/z_sub_shm.c
  examples/z_sub_thr.c
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/closures/hello_closure.rs
  src/closures/query_channel.rs
  src/closures/query_closure.rs
  src/closures/reply_closure.rs
  src/closures/response_channel.rs
  src/closures/sample_channel.rs
  src/closures/sample_closure.rs
  src/get.rs
  src/info.rs
  src/liveliness.rs
  src/queryable.rs
  src/querying_subscriber.rs
  src/scouting.rs
  src/subscriber.rs
  tests/z_api_alignment_test.c
  tests/z_api_double_drop_test.c
  tests/z_api_drop_options.c
  tests/z_api_keyexpr_drop_test.c
  tests/z_api_liveliness.c
  tests/z_int_pub_cache_query_sub_test.c
  tests/z_int_pub_sub_attachment_test.c
  tests/z_int_pub_sub_test.c
  tests/z_int_queryable_attachment_test.c
  tests/z_int_queryable_test.c
  tests/z_leak_pub_sub_test.c
  tests/z_leak_queryable_get_test.c
Labels: enhancement

#680 wrap loaned objects inside callbacks into option to pretend they are owned
  src/closures/query_channel.rs
  src/closures/response_channel.rs
  src/closures/sample_channel.rs
  src/get.rs
  src/liveliness.rs
  src/queryable.rs
  src/querying_subscriber.rs
  src/scouting.rs
  src/subscriber.rs
Labels: internal

#682 update docs regarding undefined behavior when using multiple z_bytes_writers
  include/zenoh_commons.h
  src/payload.rs
Labels: documentation, internal

#683 dev/init log from env or
  .github/workflows/ci.yml
  .readthedocs.yaml
  CMakeLists.txt
  Cargo.toml
  Cargo.toml.in
  README.md
  docs/api.rst
  examples/z_delete.c
  examples/z_get.c
  examples/z_get_liveliness.c
  examples/z_get_shm.c
  examples/z_info.c
  examples/z_liveliness.c
  examples/z_non_blocking_get.c
  examples/z_ping.c
  examples/z_ping_shm.c
  examples/z_pong.c
  examples/z_pub.c
  examples/z_pub_attachment.c
  examples/z_pub_cache.c
  examples/z_pub_shm.c
  examples/z_pub_shm_thr.c
  examples/z_pub_thr.c
  examples/z_pull.c
  examples/z_put.c
  examples/z_query_sub.c
  examples/z_queryable.c
  examples/z_queryable_shm.c
  examples/z_queryable_with_channels.c
  examples/z_scout.c
  examples/z_sub.c
  examples/z_sub_attachment.c
  examples/z_sub_liveliness.c
  examples/z_sub_shm.c
  examples/z_sub_thr.c
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/lib.rs
  src/scouting.rs
  src/session.rs
  tests/z_api_alignment_test.c
  tests/z_api_config_test.c
  tests/z_api_double_drop_test.c
  tests/z_api_drop_options.c
Labels: enhancement, api sync, api fix

#684 fix zc_init_log_from_callback name and signature
  docs/api.rst
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/lib.rs
Labels: internal, api fix

#696 add explicit closure constructors
  build.rs
  docs/api.rst
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/closures/hello_closure.rs
  src/closures/log_closure.rs
  src/closures/matching_status_closure.rs
  src/closures/query_closure.rs
  src/closures/reply_closure.rs
  src/closures/sample_closure.rs
  src/closures/zenohid_closure.rs
Labels: enhancement, api fix

#698 Rename zc_config_insert_json to zc_config_insert_json5
  docs/api.rst
  examples/parse_args.h
  examples/z_get_shm.c
  examples/z_pub_cache.c
  examples/z_pub_shm_thr.c
  examples/z_queryable_shm.c
  examples/z_sub.c
  examples/z_sub_shm.c
  examples/z_sub_thr.c
  include/zenoh_commons.h
  src/config.rs
  tests/z_api_config_test.c
  tests/z_int_pub_cache_query_sub_test.c
Labels: enhancement, api fix

#690 Documnetation page about zenoh-c types concepts
  docs/concepts.rst
  docs/index.rst
Labels: documentation

#701 Change `z_sleep_*` result type to z_result_t
  include/zenoh_commons.h
  src/platform/sleep.rs
Labels: enhancement, api sync

#702 add z_encoding_equals
  docs/api.rst
  include/zenoh_commons.h
  src/encoding.rs
  tests/z_api_encoding_test.c
Labels: enhancement, api sync

#703 add Z_FEATURE prefix to feature macros to avoid name collision
  Cargo.toml
  build.rs
  cbindgen.toml
  docs/Doxyfile
  examples/z_pub.c
  examples/z_pub_shm.c
  examples/z_scout.c
  examples/z_sub.c
  examples/z_sub_shm.c
  examples/z_sub_thr.c
  include/zenoh_commons.h
  tests/z_api_alignment_test.c
  tests/z_api_keyexpr_test.c
  tests/z_api_null_drop_test.c
  tests/z_int_pub_sub_test.c
  tests/z_int_queryable_test.c
Labels: internal, api fix

#704 Use SourceInfo accessors and builder
  Cargo.lock
  Cargo.toml
  src/commons.rs
Labels: internal

#706 fix pub_thr example to generate similar payload to rust to avoid difference in throughput
  examples/z_pub_thr.c
Labels: internal

#707 fix/reliability
  Cargo.lock
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/commons.rs
Labels: internal

#708 add z_bytes example
  examples/z_bytes.c
Labels: enhancement

#711 fix encoding constant name
  docs/api.rst
  include/zenoh_commons.h
  src/encoding.rs
Labels: bug

#715 Support for zenoh features
  .github/workflows/ci.yml
  CMakeLists.txt
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
  README.md
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/Cargo.toml
  build.rs
  include/zenoh_commons.h
  include/zenoh_macros.h
Labels: enhancement

#722 chore: update release.yml for required labels
  .github/release.yml
Labels: internal

#697 Wa shm cleanup
  Cargo.lock
  Cargo.toml
  build-resources/opaque-types/Cargo.lock
  docs/api.rst
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/shm/cleanup.rs
  src/shm/mod.rs
  tests/z_api_shm_test.c
Labels: enhancement, release, api sync

#724 documentation for view types updated
  docs/concepts.rst
Labels: documentation

#725 Add some missed methods to doc
  docs/api.rst
Labels: documentation
