Repository eclipse-zenoh/zenoh-c, pull requests merged in 2024-11, with the labels that each got.

#800 auto generate zenoh version in header from version.txt
  CMakeLists.txt
  build.rs
  include/zenoh.h
  include/zenoh_commons.h
  include/zenoh_macros.h
Labels: internal

#803 fix: Don't tag release branch during dry-run
  .github/workflows/release.yml
  ci/scripts/bump-and-tag.bash
Labels: internal

#808 build crash fix when version in format 1.0.0 (without tweak part)
  build.rs
  include/zenoh_commons.h
  include/zenoh_macros.h
Labels: internal

#815 do not hardcode linker path in .cargo/config.toml
  .cargo/config.toml
  build.rs
  ci/toolchains/TC-aarch64-unknown-linux-gnu.cmake
  ci/toolchains/TC-aarch64-unknown-linux-musl.cmake
  ci/toolchains/TC-arm-unknown-linux-gnueabi.cmake
  ci/toolchains/TC-arm-unknown-linux-gnueabihf.cmake
  ci/toolchains/TC-armv7-unknown-linux-gnueabihf.cmake
  ci/toolchains/TC-x86_64-pc-windows-gnu.cmake
  ci/toolchains/TC-x86_64-unknown-linux-gnu.cmake
  ci/toolchains/TC-x86_64-unknown-linux-musl.cmake
Labels: bug, internal

#816 to_loaned_shm -> as_loaned_shm
  examples/z_queryable_shm.c
  examples/z_sub_shm.c
  include/zenoh_commons.h
  src/zbytes.rs
Labels: release, internal, api fix

#817 Improve SHM API doc
  include/zenoh_commons.h
  src/shm/buffer/zshm.rs
  src/shm/client/shm_client.rs
  src/shm/client/shm_segment.rs
  src/shm/client_storage/mod.rs
  src/shm/protocol_implementations/posix/protocol_id.rs
  src/shm/provider/alloc_layout.rs
  src/shm/provider/shm_provider.rs
Labels: documentation, release, internal

#819 Use zenoh executor for SHM async allocation
  src/shm/provider/alloc_layout_impl.rs
  src/shm/provider/shm_provider_impl.rs
Labels: enhancement, release, internal

#820 Remove unused crates
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
Labels: enhancement, release, internal

#826 renamed z_liveliness* function to give them correct names
  build-resources/opaque-types/src/lib.rs
  docs/api.rst
  examples/z_get_liveliness.c
  examples/z_liveliness.c
  examples/z_sub_liveliness.c
  include/zenoh_commons.h
  include/zenoh_macros.h
  splitguide.yaml
  src/liveliness.rs
  tests/z_api_liveliness.c
Labels: api sync, internal
