Repository eclipse-zenoh/zenoh-c, pull requests merged in 2024-10, with the labels that each got.

#720 serialization refactoring
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/Cargo.toml
  build-resources/opaque-types/src/lib.rs
  docs/api.rst
  docs/concepts.rst
  docs/examples.rst
  examples/z_bytes.c
  examples/z_get.c
  examples/z_get_shm.c
  examples/z_non_blocking_get.c
  examples/z_ping_shm.c
  examples/z_pub.c
  examples/z_pub_attachment.c
  examples/z_pub_cache.c
  examples/z_pub_shm.c
  examples/z_pub_shm_thr.c
  examples/z_pull.c
  examples/z_put.c
  examples/z_query_sub.c
  examples/z_queryable.c
  examples/z_queryable_shm.c
  examples/z_queryable_with_channels.c
  examples/z_sub.c
  examples/z_sub_attachment.c
  examples/z_sub_shm.c
  include/zenoh_commons.h
  include/zenoh_concrete.h
  include/zenoh_macros.h
  splitguide.yaml
  src/lib.rs
  src/result.rs
  src/serialization.rs
  src/shm/cleanup.rs
  src/zbytes.rs
  tests/z_api_alignment_test.c
  tests/z_api_drop_options.c
  tests/z_api_payload_test.c
  tests/z_int_pub_cache_query_sub_test.c
  tests/z_int_pub_sub_attachment_test.c
  tests/z_int_pub_sub_test.c
  tests/z_int_queryable_attachment_test.c
  tests/z_int_queryable_test.c
  tests/z_leak_pub_sub_test.c
  tests/z_leak_queryable_get_test.c
Labels: enhancement

#729 feat: add an error code for SessionClosedError
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  include/zenoh_concrete.h
  src/get.rs
  src/publisher.rs
  src/put.rs
  src/result.rs
Labels: enhancement

#730 make serialization stable
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/Cargo.toml
  build-resources/opaque-types/src/lib.rs
  examples/z_bytes.c
  examples/z_pub_attachment.c
  examples/z_put.c
  examples/z_sub_attachment.c
  include/zenoh_commons.h
  include/zenoh_macros.h
  splitguide.yaml
  src/lib.rs
  src/serialization.rs
  tests/z_api_null_drop_test.c
  tests/z_api_payload_test.c
  tests/z_int_pub_sub_attachment_test.c
  tests/z_int_queryable_attachment_test.c
Labels: enhancement, api sync

#732 import zenoh ext with internal feature for using VarInt
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
Labels: internal

#733 added zenoh-ext/internal feature for opaque-types generator
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/Cargo.toml
Labels: internal

#739 make z_close take session by mutable reference
  docs/api.rst
  docs/examples.rst
  examples/z_delete.c
  examples/z_get.c
  examples/z_get_liveliness.c
  examples/z_get_shm.c
  examples/z_info.c
  examples/z_liveliness.c
  examples/z_non_blocking_get.c
  examples/z_ping.c
  examples/z_ping_shm.c
  examples/z_pong.c
  examples/z_pub.c
  examples/z_pub_attachment.c
  examples/z_pub_cache.c
  examples/z_pub_shm.c
  examples/z_pub_shm_thr.c
  examples/z_pub_thr.c
  examples/z_pull.c
  examples/z_put.c
  examples/z_query_sub.c
  examples/z_queryable.c
  examples/z_queryable_shm.c
  examples/z_queryable_with_channels.c
  examples/z_sub.c
  examples/z_sub_attachment.c
  examples/z_sub_liveliness.c
  examples/z_sub_shm.c
  examples/z_sub_thr.c
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/session.rs
  tests/z_api_alignment_test.c
  tests/z_api_double_drop_test.c
  tests/z_api_drop_options.c
  tests/z_api_keyexpr_drop_test.c
  tests/z_int_pub_cache_query_sub_test.c
  tests/z_int_pub_sub_attachment_test.c
  tests/z_int_pub_sub_test.c
  tests/z_int_queryable_attachment_test.c
  tests/z_int_queryable_test.c
  tests/z_leak_pub_sub_test.c
  tests/z_leak_queryable_get_test.c
Labels: enhancement, api sync, api fix

#741 serialization support for bool
  docs/api.rst
  include/zenoh_commons.h
  src/serialization.rs
Labels: enhancement, api sync, api fix

#746 Fix doxygen warnings
  include/zenoh_commons.h
  src/collections.rs
  src/keyexpr.rs
  src/liveliness.rs
  src/publisher.rs
  src/queryable.rs
  src/scouting.rs
  src/serialization.rs
  src/shm/buffer/zshmmut.rs
  src/subscriber.rs
Labels: documentation

#744 Sync lockfile with Zenoh `e9f3b37` from `2024-10-08`
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/src/lib.rs
  src/closures/query_channel.rs
  src/closures/response_channel.rs
  src/closures/sample_channel.rs
Labels: internal

#747 Add missed methods to the documentation
  docs/api.rst
Labels: documentation

#751 add ze_publication_cache_declare_background
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  docs/api.rst
  docs/examples.rst
  examples/z_queryable.c
  examples/z_queryable_shm.c
  examples/z_queryable_with_channels.c
  include/zenoh_commons.h
  src/publication_cache.rs
  src/queryable.rs
  tests/z_api_alignment_test.c
  tests/z_api_double_drop_test.c
  tests/z_int_queryable_attachment_test.c
  tests/z_int_queryable_test.c
  tests/z_leak_queryable_get_test.c
Labels: enhancement, api fix

#755 revert the renaming of implicit session functions
  docs/api.rst
  docs/examples.rst
  examples/z_liveliness.c
  examples/z_ping.c
  examples/z_ping_shm.c
  examples/z_pong.c
  examples/z_pub.c
  examples/z_pub_attachment.c
  examples/z_pub_cache.c
  examples/z_pub_shm.c
  examples/z_pub_shm_thr.c
  examples/z_pub_thr.c
  examples/z_pull.c
  examples/z_query_sub.c
  examples/z_queryable.c
  examples/z_queryable_shm.c
  examples/z_queryable_with_channels.c
  examples/z_sub.c
  examples/z_sub_attachment.c
  examples/z_sub_liveliness.c
  examples/z_sub_shm.c
  examples/z_sub_thr.c
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/keyexpr.rs
  src/liveliness.rs
  src/publication_cache.rs
  src/publisher.rs
  src/queryable.rs
  src/querying_subscriber.rs
  src/subscriber.rs
  tests/z_api_alignment_test.c
  tests/z_api_double_drop_test.c
  tests/z_api_keyexpr_drop_test.c
  tests/z_api_keyexpr_test.c
  tests/z_api_liveliness.c
  tests/z_int_pub_cache_query_sub_test.c
  tests/z_int_pub_sub_attachment_test.c
  tests/z_int_pub_sub_test.c
  tests/z_int_queryable_attachment_test.c
  tests/z_int_queryable_test.c
  tests/z_leak_pub_sub_test.c
  tests/z_leak_queryable_get_test.c
Labels: internal, api fix

#760 Readme/docs update
  README.md
  docs/concepts.rst
Labels: documentation

#761 prefix doc update
  docs/concepts.rst
Labels: documentation

#763 fix: Update opaque-types Cargo.toml during release
  ci/scripts/bump-and-tag.bash
Labels: internal

#768 moved actually stable functionality from unstable feature
  build-resources/opaque-types/src/lib.rs
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/closures/mod.rs
  src/closures/zenohid_closure.rs
  src/info.rs
  src/lib.rs
Labels: bug, release, api fix

#765 add closure typedefs for C
  build.rs
  include/zenoh_macros.h
Labels: enhancement, api sync

#772 remove unstable requirement from functionality that is stable in rust
  examples/CMakeLists.txt
  examples/z_scout.c
  include/zenoh_commons.h
  splitguide.yaml
  src/commons.rs
  src/scouting.rs
  tests/z_api_alignment_test.c
Labels: bug, internal

#770 fix: set correct debian version during release
  ci/scripts/bump-and-tag.bash
Labels: bug, internal

#775 fix package generation
  CMakeLists.txt
  install/CMakeLists.txt
  install/cpack_project_config.cmake
Labels: bug, internal

#780 fix version check for x.y.z
  CMakeLists.txt
  install/CMakeLists.txt
Labels: internal

#783 fix z_ping example
  .github/workflows/ci.yml
  CMakeLists.txt
  examples/z_ping.c
Labels: bug

#787 Fix cross compile shm
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/src/lib.rs
  include/zenoh_commons.h
  include/zenoh_macros.h
  splitguide.yaml
  src/shm/provider/shm_provider_backend.rs
  src/shm/provider/types.rs
Labels: bug, enhancement, release

#790 Add cross-compile tests to ci and fix library names
  .cargo/config.toml
  .github/workflows/ci.yml
  CMakeLists.txt
  ci/toolchains/TC-aarch64-unknown-linux-gnu.cmake
  ci/toolchains/TC-aarch64-unknown-linux-musl.cmake
  ci/toolchains/TC-arm-unknown-linux-gnueabi.cmake
  ci/toolchains/TC-armv7-unknown-linux-gnueabihf.cmake
  ci/toolchains/TC-x86_64-pc-windows-gnu.cmake
  ci/toolchains/TC-x86_64-unknown-linux-gnu.cmake
  ci/toolchains/TC-x86_64-unknown-linux-musl.cmake
  cmake/cross_build_check.cmake
  examples/CMakeLists.txt
  install/CMakeLists.txt
  install/PackageConfig.cmake.in
  install/cpack_project_config.cmake
Labels: bug, internal

#794 readme update for cross-compilation
  README.md
Labels: internal

#781 fix: change release workflow to build using cpack
  .github/workflows/ci.yml
  .github/workflows/release.yml
  ci/toolchains/TC-aarch64-apple-darwin.cmake
  ci/toolchains/TC-aarch64-unknown-linux-gnu.cmake
  ci/toolchains/TC-aarch64-unknown-linux-musl.cmake
  ci/toolchains/TC-arm-unknown-linux-gnueabi.cmake
  ci/toolchains/TC-arm-unknown-linux-gnueabihf.cmake
  ci/toolchains/TC-armv7-unknown-linux-gnueabihf.cmake
  ci/toolchains/TC-x86_64-apple-darwin.cmake
  ci/toolchains/TC-x86_64-pc-windows-gnu.cmake
  ci/toolchains/TC-x86_64-pc-windows-msvc.cmake
  ci/toolchains/TC-x86_64-unknown-linux-gnu.cmake
  ci/toolchains/TC-x86_64-unknown-linux-musl.cmake
  install/CMakeLists.txt
  install/cpack_project_config.cmake
Labels: internal

#793 fix package generation
  install/CMakeLists.txt
  install/cpack_project_config.cmake
Labels: internal
