Repository eclipse-zenoh/zenoh-c, pull requests merged in 2024-12, with the labels that each got.

#837 add querier
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/Cargo.toml
  build-resources/opaque-types/src/lib.rs
  docs/api.rst
  examples/CMakeLists.txt
  examples/parse_args.h
  examples/z_get.c
  examples/z_pub.c
  examples/z_pub_shm.c
  examples/z_querier.c
  examples/z_queryable.c
  examples/z_queryable_with_channels.c
  include/zenoh_commons.h
  include/zenoh_macros.h
  splitguide.yaml
  src/lib.rs
  src/matching.rs
  src/publisher.rs
  src/querier.rs
Labels: api sync, new feature

#831 refactor: remove unnecessary copy in examples
  examples/z_bytes.c
Labels: enhancement

#824 'history' and 'timeout_ms' options are documented
  docs/README.md
  docs/api.rst
  include/zenoh_commons.h
  src/liveliness.rs
  src/shm/provider/alloc_layout.rs
  src/shm/provider/shm_provider.rs
Labels: documentation

#835 support internal/unstable close builder API
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/Cargo.toml
  build-resources/opaque-types/src/lib.rs
  include/zenoh_commons.h
  include/zenoh_macros.h
  splitguide.yaml
  src/close.rs
  src/lib.rs
  src/session.rs
  tests/z_api_session_test.c
Labels: enhancement, release, api sync

#846 inforrect branch reference in Cargo.toml fixed
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
  build-resources/opaque-types/Cargo.lock
Labels: internal

#847 fix incorrect zenoh repo
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
Labels: bug, release, internal

#844 examples' command line arguments aligned with those in rust. Failures in shared memory examples fixed
  examples/parse_args.h
  examples/z_delete.c
  examples/z_get.c
  examples/z_get_liveliness.c
  examples/z_get_shm.c
  examples/z_info.c
  examples/z_liveliness.c
  examples/z_non_blocking_get.c
  examples/z_ping.c
  examples/z_ping_shm.c
  examples/z_pong.c
  examples/z_pub.c
  examples/z_pub_attachment.c
  examples/z_pub_cache.c
  examples/z_pub_shm.c
  examples/z_pub_shm_thr.c
  examples/z_pub_thr.c
  examples/z_pull.c
  examples/z_put.c
  examples/z_querier.c
  examples/z_query_sub.c
  examples/z_queryable.c
  examples/z_queryable_shm.c
  examples/z_queryable_with_channels.c
  examples/z_sub.c
  examples/z_sub_attachment.c
  examples/z_sub_liveliness.c
  examples/z_sub_shm.c
  examples/z_sub_thr.c
Labels: bug, internal

#850 Fix calling find_package(zenohc) twice in CMake
  install/PackageConfig.cmake.in
Labels: bug

#853 stabilize liveliness API
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/src/lib.rs
  examples/CMakeLists.txt
  include/zenoh_commons.h
  include/zenoh_macros.h
  splitguide.yaml
  src/lib.rs
  src/liveliness.rs
  src/publication_cache.rs
  src/querying_subscriber.rs
  tests/CMakeLists.txt
Labels: new feature

#857 Add deprecation allowance for builder.rs
  build-resources/opaque-types/src/lib.rs
Labels: internal

#856 add --cfg arg support
  examples/parse_args.h
  examples/z_liveliness.c
Labels: enhancement, api sync

#859 fix priority parsing
  examples/parse_args.h
  examples/z_pub_thr.c
Labels: bug

#854 Advanced pub sub
  build-resources/opaque-types/src/lib.rs
  docs/api.rst
  examples/CMakeLists.txt
  examples/z_advanced_pub.c
  examples/z_advanced_sub.c
  examples/z_delete.c
  examples/z_get_liveliness.c
  examples/z_liveliness.c
  examples/z_pull.c
  examples/z_sub.c
  examples/z_sub_liveliness.c
  examples/z_sub_shm.c
  include/zenoh_commons.h
  include/zenoh_macros.h
  splitguide.yaml
  src/advanced_publisher.rs
  src/advanced_subscriber.rs
  src/closures/miss_closure.rs
  src/closures/mod.rs
  src/get.rs
  src/keyexpr.rs
  src/lib.rs
  src/liveliness.rs
  src/publication_cache.rs
  src/publisher.rs
  src/put.rs
  src/querier.rs
  src/queryable.rs
  src/querying_subscriber.rs
  src/subscriber.rs
  tests/CMakeLists.txt
  tests/z_int_advanced_pub_sub_test.c
  tests/z_int_helpers.h
Labels: enhancement, api sync

#864 advanced publisher/subscriber options contains cache options inside
  examples/z_advanced_pub.c
  examples/z_advanced_sub.c
  include/zenoh_commons.h
  src/advanced_publisher.rs
  src/advanced_subscriber.rs
  tests/z_int_advanced_pub_sub_test.c
Labels: internal, api fix

#866 fix docs
  docs/api.rst
Labels: documentation

#863 fix: exclude internal from automatic changelog
  .github/release.yml
Labels: internal

#862 Add CI for checking markdown format.
  .github/workflows/ci.yml
  .markdownlint.yaml
  README.md
  docs/README.md
Labels: internal

#865 add possibility to get contiguous view of z_bytes data when it is not fragmented
  docs/api.rst
  include/zenoh_commons.h
  src/zbytes.rs
  tests/z_api_payload_test.c
Labels: enhancement

#861 Shm mutation example
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  docs/api.rst
  examples/z_sub_shm.c
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/commons.rs
  src/get.rs
  src/queryable.rs
  src/shm/buffer/zshm.rs
  src/zbytes.rs
Labels: enhancement, release, api sync, api fix

#871 add missing subscriber methods
  docs/api.rst
  include/zenoh_commons.h
  src/advanced_subscriber.rs
  src/subscriber.rs
Labels: enhancement, api sync

#875 Fix typo in query_closure.rs
  src/closures/query_closure.rs
Labels: bug, internal

#878 Fix z_get query parameters
  examples/z_get.c
Labels: bug

#879 Fix liveliness timeout type
  include/zenoh_commons.h
  src/liveliness.rs
Labels: bug
