Repository eclipse-zenoh/zenoh-c, pull requests merged in 2025-02, with the labels that each got.

#901 Update git branch
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/Cargo.toml
Labels: internal

#913 Adopt the different congestion control defaults as in Rust
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/Cargo.toml
  include/zenoh_commons.h
  include/zenoh_constants.h
  src/advanced_publisher.rs
  src/commons.rs
  src/get.rs
  src/publisher.rs
  src/put.rs
  src/querier.rs
  src/queryable.rs
Labels: bug, internal

#920 Eclipse zenoh bot/post release 1.2.1
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/Cargo.toml
  version.txt
Labels: internal

#923 take operation accepts mutable loaned reference for types which supports it
  build.rs
  docs/README.md
  docs/concepts.rst
  include/zenoh_commons.h
  include/zenoh_macros.h
  src/collections.rs
  src/commons.rs
  src/encoding.rs
  src/get.rs
  src/keyexpr.rs
  src/queryable.rs
  src/scouting.rs
  src/serialization.rs
  src/transmute.rs
  src/zbytes.rs
  tests/z_api_null_drop_test.c
Labels: enhancement, api fix
