Repository eclipse-zenoh/zenoh-c, pull requests merged in 2025-01, with the labels that each got.

#880 latest zenoh
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
Labels: bug, internal

#883 bump zenoh: Fix GarbageCollect policy for corner cases
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
Labels: bug, release

#885 fix docs/align examples with rust
  README.md
  build-resources/opaque-types/src/lib.rs
  docs/examples.rst
  examples/README.md
  examples/z_pub_thr.c
  examples/z_put.c
  examples/z_queryable.c
  examples/z_scout.c
  examples/z_storage.c
  examples/z_sub_thr.c
  include/zenoh_commons.h
  src/keyexpr.rs
  src/session.rs
Labels: documentation

#887 add internal functions for (de)composing encoding to/from id and string
  include/zenoh_commons.h
  src/encoding.rs
Labels: internal

#886 heartbeat support for advanced pub/sub
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  docs/api.rst
  examples/z_advanced_pub.c
  examples/z_advanced_sub.c
  include/zenoh_commons.h
  src/advanced_publisher.rs
  src/advanced_subscriber.rs
  tests/z_int_advanced_pub_sub_test.c
Labels: enhancement, api fix

#891 support for advanced pubs default recovery option without last sample miss detection
  docs/api.rst
  examples/z_advanced_sub.c
  include/zenoh_commons.h
  src/advanced_publisher.rs
  src/advanced_subscriber.rs
  tests/z_int_advanced_pub_sub_test.c
Labels: enhancement, api sync, api fix

#894 Rename zc_liveliness_declare_background_subscriber and make it stable
  docs/api.rst
  include/zenoh_commons.h
  src/liveliness.rs
Labels: api sync, internal

#897 up zenoh
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/Cargo.toml
Labels: api sync, internal

#898 Rename matching methods and types from `zc_*` to `z_*`
  build-resources/opaque-types/src/lib.rs
  docs/api.rst
  examples/z_pub.c
  examples/z_pub_shm.c
  examples/z_querier.c
  include/zenoh_commons.h
  include/zenoh_macros.h
  splitguide.yaml
  src/advanced_publisher.rs
  src/closures/matching_status_closure.rs
  src/matching.rs
  src/publisher.rs
  src/querier.rs
Labels: enhancement, api sync
