Repository eclipse-zenoh/zenoh-c, pull requests merged in 2025-07, with the labels that each got.

#1045 ci: update release workflow to use latest runners
  .github/workflows/release.yml
Labels: internal

#1046 polish shm
  examples/z_get_shm.c
  examples/z_ping_shm.c
  examples/z_pub_shm.c
  examples/z_pub_shm_thr.c
  examples/z_queryable_shm.c
  include/zenoh_commons.h
  include/zenoh_constants.h
  src/shm/protocol_implementations/posix/posix_shm_provider.rs
  src/shm/provider/alloc_layout.rs
  src/shm/provider/alloc_layout_impl.rs
  src/shm/provider/shm_provider.rs
  src/shm/provider/types.rs
  tests/z_api_shm_test.c
Labels: enhancement, release, api sync, api fix

#1056 add missing functions to docs
  docs/api.rst
Labels: bug, internal

#1057 fix strlen calls on null pointers
  src/collections.rs
  src/config.rs
  src/encoding.rs
  src/get.rs
  src/keyexpr.rs
  src/lib.rs
  src/querier.rs
  src/serialization.rs
  src/zbytes.rs
Labels: bug

#1054 add CongestionControl::BlockFirst
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  src/commons.rs
Labels: new feature

#1059 stabilize querier, matching and locality
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/src/lib.rs
  examples/CMakeLists.txt
  examples/z_pub.c
  examples/z_pub_shm.c
  examples/z_querier.c
  include/zenoh_commons.h
  src/closures/mod.rs
  src/commons.rs
  src/lib.rs
  src/matching.rs
  src/publication_cache.rs
  src/publisher.rs
  src/querier.rs
  src/queryable.rs
  src/querying_subscriber.rs
  src/subscriber.rs
Labels: enhancement, api sync

#1061 stabilize locality for get and put
  include/zenoh_commons.h
  src/get.rs
  src/put.rs
Labels: bug, api fix

#1058 [ZEN-587] Change `replier_id` type to `z_entity_global_id_t`
  Cargo.lock
  include/zenoh_commons.h
  src/get.rs
Labels: api sync, breaking-change

#1071 fix: MSVC Error C2059
  examples/z_advanced_pub.c
  examples/z_pub.c
  examples/z_querier.c
Labels: bug
