Repository eclipse-zenoh/zenoh-c, pull requests merged in 2025-06, with the labels that each got.

#1023 fix: avoid updating Cargo.lock to version 4
  ci/scripts/bump-and-tag.bash
Labels: internal

#1030 Update doc examples according to recent API, fix typos
  docs/examples.rst
Labels: documentation

#1032 examples: don't ignore return status code
  examples/z_ping.c
  examples/z_ping_shm.c
  examples/z_pong.c
  examples/z_pub.c
  examples/z_pub_shm.c
  examples/z_querier.c
Labels: internal

#1038 Fix build with panic="abort"
  src/platform/synchronization.rs
Labels: bug

#1040 do not build opaque types in source tree
  .gitignore
  build.rs
  buildrs/cbindgen_generator.rs
  buildrs/opaque_types_generator.rs
  src/opaque_types/.gitkeep
  src/opaque_types/mod.rs
Labels: bug

#1025 docs: update example commands to use -p flag instead of -v for payload
  examples/README.md
Labels: bug

#1041 CMP0111 requires IMPORTED_LOCATION or IMPORTED_IMPLIB being set
  CMakeLists.txt
Labels: bug
