Repository eclipse-zenoh/zenoh-c, pull requests merged in 2025-03, with the labels that each got.

#938 run apt-get update for Cross compile on ubuntu-latest
  .github/workflows/ci.yml
Labels: internal

#942 Fix dummy shm provider definition
  build-resources/opaque-types/src/lib.rs
Labels: release, internal

#930 support for api changes in namespaces PR
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  include/zenoh_commons.h
  src/publication_cache.rs
Labels: api sync, internal, api fix

#948 chore: better name for workflow step
  .github/workflows/ci.yml
Labels: internal

#906 add delay to memory leak tests to avoid flakiness
  tests/z_leak_pub_sub_test.c
  tests/z_leak_queryable_get_test.c
Labels: internal

#953 fix: add ci check for rust 1.75
  .github/workflows/ci.yml
Labels: internal

#933 Bump Rust toolchain to 1.85
  Cargo.toml
  Cargo.toml.in
  README.md
  build-resources/opaque-types/Cargo.toml
  include/zenoh_commons.h
  rust-toolchain.toml
  src/config.rs
  src/platform/random.rs
  src/queryable.rs
  tests/z_leak_queryable_get_test.c
Labels: dependencies

#955 Build rs modularize
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
  build.rs
  buildrs/cbindgen_generator.rs
  buildrs/common_helpers.rs
  buildrs/mod.rs
  buildrs/opaque_types_generator.rs
  buildrs/splitguide.rs
Labels: internal

#957 cmake: add USES_TERMINAL in custom command
  CMakeLists.txt
Labels: enhancement

#964 fix: bump build-dependencies during release
  ci/scripts/bump-and-tag.bash
Labels: internal

#848 Nolocal close
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/src/lib.rs
  src/close.rs
Labels: release, api sync, internal

#967 Post release 1.3.0
  .readthedocs.yaml
  Cargo.lock
  Cargo.toml
  Cargo.toml.in
  build-resources/opaque-types/Cargo.toml
  version.txt
Labels: internal

#969 sporadic heartbeat support
  Cargo.lock
  build-resources/opaque-types/Cargo.lock
  examples/z_advanced_pub.c
  include/zenoh_commons.h
  src/advanced_publisher.rs
Labels: enhancement
