Repository eclipse-zenoh/zenoh-c, pull requests merged in 2025-04, with the labels that each got.

#973 chore: update ubuntu runners to ubuntu-24.04
  .github/workflows/release.yml
Labels: internal

#972 replaced ~ to $HOME in CI as the ~ doesn't always work
  .github/workflows/ci.yml
Labels: internal

#979 Update cargo git branch
  Cargo.lock
  Cargo.toml
  build-resources/opaque-types/Cargo.lock
  build-resources/opaque-types/Cargo.toml
Labels: internal

#981 Zero Posix SHM provider if it's creation fails
  src/shm/protocol_implementations/posix/posix_shm_provider.rs
Labels: enhancement, release, internal

#982 Make build config case-insensitive as it should be
  CMakeLists.txt
Labels: bug, release, internal

#984 Rust entrypoint
  Cargo.toml
  Cargo.toml.in
  src/lib.rs
Labels: bug, release

#985 replace extern const strings with macro defines
  include/zenoh_commons.h
  include/zenoh_constants.h
  src/config.rs
Labels: bug

#989 fix z_api_liveliness_test
  tests/z_api_liveliness.c
Labels: bug

#998 styles: remove the trailing spaces in cmake file
  CMakeLists.txt
Labels: internal

#469 Fix installation when ZENOHC_CUSTOM_TARGET is not set and CARGO_BUILD_TARGET env variable is set
  CMakeLists.txt
Labels: bug
