Repository eclipse-zenoh/zenoh-c, pull requests merged in 2025-05, with the labels that each got.

#999 Add SONAME on linux cdylib
  CMakeLists.txt
  build.rs
  install/PackageConfig.cmake.in
Labels: bug, internal

#1010 build.rs lint fix
  build.rs
Labels: internal

#1020 remove suffix d from library names in debug mode
  CMakeLists.txt
  README.md
Labels: bug
